parameters:
    database_driver:   pdo_mysql
    database_host:     mysql.ekreative.com
    database_port:     ~
    database_name:     rice_deckkeeper
    database_user:     sasha
    database_password: 

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
