fos_rest:
    view:
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig

services:
    xml_parser:
        class:        Diver\PriceLisrBundle\XmlParser\XmlParser
        arguments:
                entityManager: "@doctrine.orm.entity_manager"