diver_price_lisr_xml_upload:
    pattern:  /xml/upload
    defaults: { _controller: DiverPriceLisrBundle:Xml:index }

diver_price_lisr_xml_parse:
    pattern:  /xml/parse
    defaults: { _controller: DiverPriceLisrBundle:Xml:parse }

DiverPriceLisrBundle_categories:
    resource: "@DiverPriceLisrBundle/Resources/config/routing/categories.yml"
    prefix:   /categories

DiverPriceLisrBundle_items:
    resource: "@DiverPriceLisrBundle/Resources/config/routing/items.yml"
    prefix:   /items

DiverPriceLisrBundle_rest:
    resource: "@DiverPriceLisrBundle/Resources/config/routing/rest.yml"
    prefix:   /rest